/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import static org.junit.Assert.*;

import java.util.List;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Assert;
import org.junit.Before;
import org.junit.BeforeClass;

public class LibraryTest {
	
	WebDriver driver;
	
	@Before
	public void openBrowser()
	{
		driver = new ChromeDriver();
		driver.manage().window().maximize();
	}
	
    @Test
    public void ChromeTest()
    {
    	// Arrange
    	String urlWiki = "https://en.wikipedia.org/wiki/Main_Page";
    	String expectedResult = "FIFA World Cup";
    	String idSearchBar = "search";
    	String idSearchButton = "searchButton";
    	String xpathFirstLink = "//*[@id=\"mw-content-text\"]/div/p[1]/a";
    	String idTitle = "firstHeading";
    	
    	// Act
    	driver.get(urlWiki);
    	driver.findElement(By.name(idSearchBar)).sendKeys("World Cup");
    	driver.findElement(By.id(idSearchButton)).click();
    	driver.findElement(By.xpath(xpathFirstLink)).click();
    	WebElement title = driver.findElement(By.id(idTitle));
    	
    	// Assert
    	Assert.assertEquals(expectedResult, title.getText());
    }
    
    @Test
    public void testFail()
    {
    	Assert.assertTrue(true);
    }
    
    @After
    public void closeBrowser()
    {
    	driver.quit();
    }
     
}
